name: test

on: push

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15"

      - run: go build .
      - run: go vet ./...
      - run: go test ./...
